version: '3.8'

services:
  pgsql:
      build: ./gis
      container_name: gis-pgsql-${SERVER}
      image: gzileni/postgis:wharp
      restart: always
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        PGPORT: ${PGPORT}
      ports:
        - ${PGPORT}:${PGPORT}
      networks:
        - gis-network
      volumes:
        - .${PGDATA}:/var/lib/postgresql/data
      
  geoserver:
    container_name: gis-geoserver-${SERVER}
    image: docker.osgeo.org/geoserver:2.21.1
    restart: always
    depends_on:
      - pgsql
    environment:
        INSTALL_EXTENSIONS: true
        STABLE_EXTENSIONS: ${STABLE_EXTENSIONS}
        EXTRA_JAVA_OPTS: -Xms1G -Xmx2G
    volumes:
        - ./data/geoserver:/opt/geoserver_data
    ports:
      - ${PORTGS}:${PORTGS}
    networks:
      - gis-network

networks:
   gis-network:
      name: gis
      driver: bridge
      ipam:
         driver: default
         config:
            - subnet: 192.168.200.0/24